[project]
name = "hw4-computing-dsdm-campos-gutierrez"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datetime>=5.5",
    "geopy>=2.4.1",
    "pandas>=2.3.3",
]
